# Generated by Django 5.0.1 on 2024-01-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='published_date',
            field=models.CharField(max_length=100),
        ),
    ]
