# Generated by Django 4.2.7 on 2024-01-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20240129_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='book_id',
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
